enum AuditAction {
  SPECIAL_REMISSION_ADD = 'CREATE_SPECIAL_REMISSION',
  SPECIAL_REMISSION_EDIT = 'EDIT_SPECIAL_REMISSION',
  SPECIAL_REMISSION_DELETE = 'DELETE_SPECIAL_REMISSION',

  TIME_SPENT_AS_APPEAL_APPLICANT_ADD = 'CREATE_TIME_SPENT_AS_APPEAL_APPLICANT',
  TIME_SPENT_AS_APPEAL_APPLICANT_EDIT = 'EDIT_TIME_SPENT_AS_APPEAL_APPLICANT',
  TIME_SPENT_AS_APPEAL_APPLICANT_DELETE = 'DELETE_TIME_SPENT_AS_APPEAL_APPLICANT',

  TAGGED_BAIL_ADD = 'CREATE_TAGGED_BAIL',
  TAGGED_BAIL_EDIT = 'EDIT_TAGGED_BAIL',
  TAGGED_BAIL_DELETE = 'DELETE_TAGGED_BAIL',

  LAWFULLY_AT_LARGE_ADD = 'CREATE_LAWFULLY_AT_LARGE',
  LAWFULLY_AT_LARGE_EDIT = 'EDIT_LAWFULLY_AT_LARGE',
  LAWFULLY_AT_LARGE_DELETE = 'DELETE_LAWFULLY_AT_LARGE',

  UNLAWFULLY_AT_LARGE_EDIT = 'EDIT_UNLAWFULLY_AT_LARGE',
  UNLAWFULLY_AT_LARGE_ADD = 'CREATE_UNLAWFULLY_AT_LARGE',
  UNLAWFULLY_AT_LARGE_DELETE = 'DELETE_UNLAWFULLY_AT_LARGE',

  RESTORATION_OF_ADDITIONAL_DAYS_AWARDED_ADD = 'CREATE_RESTORATION_OF_ADDITIONAL_DAYS_AWARDED',
  RESTORATION_OF_ADDITIONAL_DAYS_AWARDED_EDIT = 'EDIT_RESTORATION_OF_ADDITIONAL_DAYS_AWARDED',
  RESTORATION_OF_ADDITIONAL_DAYS_AWARDED_DELETE = 'DELETE_RESTORATION_OF_ADDITIONAL_DAYS_AWARDED',

  ADDITIONAL_DAYS_AWARDED_APPROVE = 'APPROVE_ADDITIONAL_DAYS_AWARDED',

  CUSTODY_ABROAD_ADD = 'CREATE_CUSTODY_ABROAD',
  CUSTODY_ABROAD_EDIT = 'EDIT_CUSTODY_ABROAD',
  CUSTODY_ABROAD_DELETE = 'DELETE_CUSTODY_ABROAD',

  REMAND_ADD = 'CREATE_REMAND',
  REMAND_EDIT = 'EDIT_REMAND',
  REMAND_DELETE = 'DELETE_REMAND',
}

export default AuditAction
