enum AuditAction {
  SPECIAL_REMISSION_ADD = 'CREATE_SPECIAL_REMISSION',
  SPECIAL_REMISSION_EDIT = 'EDIT_SPECIAL_REMISSION',
  SPECIAL_REMISSION_DELETE = 'DELETE_SPECIAL_REMISSION',
  TIME_SPENT_AS_APPEAL_APPLICANT_ADD = 'CREATE_TIME_SPENT_AS_APPEAL_APPLICANT',
  TIME_SPENT_AS_APPEAL_APPLICANT_EDIT = 'EDIT_TIME_SPENT_AS_APPEAL_APPLICANT',
  TIME_SPENT_AS_APPEAL_APPLICANT_DELETE = 'DELETE_TIME_SPENT_AS_APPEAL_APPLICANT',
}

export default AuditAction
