enum AuditAction {
  SPECIAL_REMISSION_ADD = 'CREATE_SPECIAL_REMISSION',
  SPECIAL_REMISSION_EDIT = 'EDIT_SPECIAL_REMISSION',
  SPECIAL_REMISSION_DELETE = 'DELETE_SPECIAL_REMISSION',
}

export default AuditAction
