const adjudications = [
  {
    adjudicationNumber: 1296861,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails:
      'WauNpDdByswUvzOnDbnUhmrcpGIVMGKvDgtCTRJRuhYzfIJfGbZhGEhLgCiCKowBZpWORYFyWauNpDdByswUvzOnDbnUhmrcpGIVMGKvDgtCTRJRuhYzfIJfGbZhGEhLgCiCKowBZpWORYF',
    reportNumber: 1278212,
    reportType: "Governor's Report",
    reporterFirstName: 'YDFISOOPHER',
    reporterLastName: 'FATALIE',
    reportTime: '2016-04-16T13:21:00',
    hearings: [
      {
        oicHearingId: 1697175,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-30T14:56:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'zvWAzvW',
        comment: 'WW',
        results: [],
      },
      {
        oicHearingId: 1685096,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'JIJJIJ',
        results: [],
      },
      {
        oicHearingId: 1703902,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:03:00',
        establishment: 'Haverigg (HMP)',
        location: 'Scafell Wing',
        otherRepresentatives: 'ASUzASU',
        results: [
          {
            oicOffenceCode: '51:1',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Commits any assault',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 26,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'zBgdbgawxpEfaQloXDBjlTzBgdbgawxpEfaQloXDBjl',
                sanctionSeq: 3,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 1296857,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails:
      'bpELIrswJXbUHQGgLFUBqiQBsWAKRCUsuFZdlfNPoITBlEDfuVceoFATMEbpELIrswJXbUHQGgLFUBqiQBsWAKRCUsuFZdlfNPoITBlEDfuVceoFATME',
    reportNumber: 1278208,
    reportType: "Governor's Report",
    reporterFirstName: 'YDFISOOPHER',
    reporterLastName: 'FATALIE',
    reportTime: '2016-04-16T13:13:00',
    hearings: [
      {
        oicHearingId: 1697174,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-22T14:55:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'KXIAKXI',
        comment: 'ZZ',
        results: [],
      },
      {
        oicHearingId: 1685088,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'BXABXA',
        results: [],
      },
      {
        oicHearingId: 1703903,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:30:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'mOKxmOK',
        results: [
          {
            oicOffenceCode: '51:22',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Disobeys any lawful order',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 14,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'JBweLvAMNKvOVIPBqsxnNWVRJBweLvAMNKvOVIPBqsxnNWV',
                sanctionSeq: 4,
                consecutiveSanctionSeq: 5,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 1296839,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails: 'cFlxuiADszvlyKvbInisOxGtZHIUPMCaJpJqbXgGEgPZdcFlxuiADszvlyKvbInisOxGtZHIUPMCaJpJqbXgGEgPZd',
    reportNumber: 1278189,
    reportType: "Governor's Report",
    reporterFirstName: 'DILBNELIWA',
    reporterLastName: 'LINDAYLA',
    reportTime: '2016-04-16T12:40:00',
    hearings: [
      {
        oicHearingId: 1697167,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-22T14:52:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'WrfyWrf',
        comment: 'UU',
        results: [],
      },
      {
        oicHearingId: 1685041,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'jiZjiZ',
        results: [],
      },
      {
        oicHearingId: 1703908,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:03:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'BnmLBnm',
        results: [
          {
            oicOffenceCode: '51:5',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Intentionally endangers the health or personal safety of others or, by his conduct, is reckless whether such health or personal safety is endangered',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 26,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'spqtPUUngnAHwTgoGHyKtirhspqtPUUngnAHwTgoGHyKtirh',
                sanctionSeq: 1,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 1296855,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails:
      'rzLlfWjHMTnVxqcxOGazFXZgdwHmpHFqRDsjYYXPPkAuSyhqHwZQfTRVvSYUdpxeXgFVOANeqauYVGWktgDUaWLNVQEBNUtmQFQhyuUxXUoBanGozrzLlfWjHMTnVxqcxOGazFXZgdwHmpHFqRDsjYYXPPkAuSyhqHwZQfTRVvSYUdpxeXgFVOANeqauYVGWktgDUaWLNVQEBNUtmQFQhyuUxXUoBanGoz',
    reportNumber: 1278206,
    reportType: "Governor's Report",
    reporterFirstName: 'AJNNECE',
    reporterLastName: 'CAROLD',
    reportTime: '2016-04-16T13:01:00',
    hearings: [
      {
        oicHearingId: 1697173,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-22T14:54:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'RwRdRwR',
        comment: 'ee',
        results: [],
      },
      {
        oicHearingId: 1685081,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'QVcQVc',
        results: [],
      },
      {
        oicHearingId: 1703904,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:30:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'qZhbqZh',
        results: [
          {
            oicOffenceCode: '51:1',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Commits any assault',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 26,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'ibuvIjhvEfItAKeHtEPibuvIjhvEfItAKeHtEP',
                sanctionSeq: 2,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 1296846,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails:
      'JxIPJubhRvBMuSKvCdBpEcZhchNUySsGECoQDvwexcVkbAWZKItlJxIPJubhRvBMuSKvCdBpEcZhchNUySsGECoQDvwexcVkbAWZKItl',
    reportNumber: 1278197,
    reportType: "Governor's Report",
    reporterFirstName: 'DILBNELIWA',
    reporterLastName: 'LINDAYLA',
    reportTime: '2016-04-16T12:50:00',
    hearings: [
      {
        oicHearingId: 1697172,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-22T14:54:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'gwdugwd',
        comment: 'KK',
        results: [],
      },
      {
        oicHearingId: 1685061,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'ffbffb',
        results: [],
      },
      {
        oicHearingId: 1703906,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:30:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'UZCCUZC',
        results: [
          {
            oicOffenceCode: '51:1',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Commits any assault',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 26,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'xREMNsMOQvgrZbsnGtEZoxREMNsMOQvgrZbsnGtEZo',
                sanctionSeq: 5,
              },
            ],
          },
        ],
      },
    ],
  },
]

export default adjudications
