const adjudicationsSearchNoReview = {
  results: {
    content: [
      {
        adjudicationNumber: 1296861,
        reportTime: '2016-04-16T13:21:00',
        agencyIncidentId: 1278212,
        agencyId: 'HVI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '1296861/1',
            offenceCode: '51:1',
            offenceDescription: 'Commits any assault',
            findingCode: 'PROVED',
          },
        ],
      },
      {
        adjudicationNumber: 1296857,
        reportTime: '2016-04-16T13:13:00',
        agencyIncidentId: 1278208,
        agencyId: 'HVI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '1296857/1',
            offenceCode: '51:22',
            offenceDescription: 'Disobeys any lawful order',
            findingCode: 'PROVED',
          },
        ],
      },
      {
        adjudicationNumber: 1296855,
        reportTime: '2016-04-16T13:01:00',
        agencyIncidentId: 1278206,
        agencyId: 'HVI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '1296855/1',
            offenceCode: '51:1',
            offenceDescription: 'Commits any assault',
            findingCode: 'PROVED',
          },
        ],
      },
      {
        adjudicationNumber: 1296846,
        reportTime: '2016-04-16T12:50:00',
        agencyIncidentId: 1278197,
        agencyId: 'HVI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '1296846/1',
            offenceCode: '51:1',
            offenceDescription: 'Commits any assault',
            findingCode: 'PROVED',
          },
        ],
      },
      {
        adjudicationNumber: 1296839,
        reportTime: '2016-04-16T12:40:00',
        agencyIncidentId: 1278189,
        agencyId: 'HVI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '1296839/1',
            offenceCode: '51:5',
            offenceDescription:
              'Intentionally endangers the health or personal safety of others or, by his conduct, is reckless whether such health or personal safety is endangered',
            findingCode: 'PROVED',
          },
        ],
      },
    ],
    pageable: {
      pageNumber: 0,
      pageSize: 1000,
      sort: { empty: true, unsorted: true, sorted: false },
      offset: 0,
      paged: true,
      unpaged: false,
    },
    totalPages: 1,
    totalElements: 5,
    last: true,
    size: 1000,
    number: 0,
    sort: { empty: true, unsorted: true, sorted: false },
    first: true,
    numberOfElements: 5,
    empty: false,
  },
  offences: [
    { id: '1', code: '51:1', description: 'Commits any assault' },
    { id: '48', code: '51:22', description: 'Disobeys any lawful order' },
    {
      id: '6',
      code: '51:5',
      description:
        'Intentionally endangers the health or personal safety of others or, by his conduct, is reckless whether such health or personal safety is endangered',
    },
  ],
  agencies: [{ agencyId: 'HVI', description: 'Haverigg (HMP)', active: true }],
}

const adjudicationsNoReview = [
  {
    adjudicationNumber: 1296861,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails:
      'WauNpDdByswUvzOnDbnUhmrcpGIVMGKvDgtCTRJRuhYzfIJfGbZhGEhLgCiCKowBZpWORYFyWauNpDdByswUvzOnDbnUhmrcpGIVMGKvDgtCTRJRuhYzfIJfGbZhGEhLgCiCKowBZpWORYF',
    reportNumber: 1278212,
    reportType: "Governor's Report",
    reporterFirstName: 'YDFISOOPHER',
    reporterLastName: 'FATALIE',
    reportTime: '2016-04-16T13:21:00',
    hearings: [
      {
        oicHearingId: 1697175,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-30T14:56:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'zvWAzvW',
        comment: 'WW',
        results: [],
      },
      {
        oicHearingId: 1685096,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'JIJJIJ',
        results: [],
      },
      {
        oicHearingId: 1703902,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:03:00',
        establishment: 'Haverigg (HMP)',
        location: 'Scafell Wing',
        otherRepresentatives: 'ASUzASU',
        results: [
          {
            oicOffenceCode: '51:1',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Commits any assault',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 26,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'zBgdbgawxpEfaQloXDBjlTzBgdbgawxpEfaQloXDBjl',
                sanctionSeq: 3,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 1296857,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails:
      'bpELIrswJXbUHQGgLFUBqiQBsWAKRCUsuFZdlfNPoITBlEDfuVceoFATMEbpELIrswJXbUHQGgLFUBqiQBsWAKRCUsuFZdlfNPoITBlEDfuVceoFATME',
    reportNumber: 1278208,
    reportType: "Governor's Report",
    reporterFirstName: 'YDFISOOPHER',
    reporterLastName: 'FATALIE',
    reportTime: '2016-04-16T13:13:00',
    hearings: [
      {
        oicHearingId: 1697174,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-22T14:55:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'KXIAKXI',
        comment: 'ZZ',
        results: [],
      },
      {
        oicHearingId: 1685088,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'BXABXA',
        results: [],
      },
      {
        oicHearingId: 1703903,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:30:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'mOKxmOK',
        results: [
          {
            oicOffenceCode: '51:22',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Disobeys any lawful order',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 14,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'JBweLvAMNKvOVIPBqsxnNWVRJBweLvAMNKvOVIPBqsxnNWV',
                sanctionSeq: 4,
                consecutiveSanctionSeq: 5,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 1296839,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails: 'cFlxuiADszvlyKvbInisOxGtZHIUPMCaJpJqbXgGEgPZdcFlxuiADszvlyKvbInisOxGtZHIUPMCaJpJqbXgGEgPZd',
    reportNumber: 1278189,
    reportType: "Governor's Report",
    reporterFirstName: 'DILBNELIWA',
    reporterLastName: 'LINDAYLA',
    reportTime: '2016-04-16T12:40:00',
    hearings: [
      {
        oicHearingId: 1697167,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-22T14:52:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'WrfyWrf',
        comment: 'UU',
        results: [],
      },
      {
        oicHearingId: 1685041,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'jiZjiZ',
        results: [],
      },
      {
        oicHearingId: 1703908,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:03:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'BnmLBnm',
        results: [
          {
            oicOffenceCode: '51:5',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Intentionally endangers the health or personal safety of others or, by his conduct, is reckless whether such health or personal safety is endangered',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 26,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'spqtPUUngnAHwTgoGHyKtirhspqtPUUngnAHwTgoGHyKtirh',
                sanctionSeq: 1,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 1296855,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails:
      'rzLlfWjHMTnVxqcxOGazFXZgdwHmpHFqRDsjYYXPPkAuSyhqHwZQfTRVvSYUdpxeXgFVOANeqauYVGWktgDUaWLNVQEBNUtmQFQhyuUxXUoBanGozrzLlfWjHMTnVxqcxOGazFXZgdwHmpHFqRDsjYYXPPkAuSyhqHwZQfTRVvSYUdpxeXgFVOANeqauYVGWktgDUaWLNVQEBNUtmQFQhyuUxXUoBanGoz',
    reportNumber: 1278206,
    reportType: "Governor's Report",
    reporterFirstName: 'AJNNECE',
    reporterLastName: 'CAROLD',
    reportTime: '2016-04-16T13:01:00',
    hearings: [
      {
        oicHearingId: 1697173,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-22T14:54:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'RwRdRwR',
        comment: 'ee',
        results: [],
      },
      {
        oicHearingId: 1685081,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'QVcQVc',
        results: [],
      },
      {
        oicHearingId: 1703904,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:30:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'qZhbqZh',
        results: [
          {
            oicOffenceCode: '51:1',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Commits any assault',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 26,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'ibuvIjhvEfItAKeHtEPibuvIjhvEfItAKeHtEP',
                sanctionSeq: 2,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 1296846,
    incidentTime: '2016-04-15T15:45:00',
    establishment: 'Haverigg (HMP)',
    interiorLocation: 'Fairfield Wing',
    incidentDetails:
      'JxIPJubhRvBMuSKvCdBpEcZhchNUySsGECoQDvwexcVkbAWZKItlJxIPJubhRvBMuSKvCdBpEcZhchNUySsGECoQDvwexcVkbAWZKItl',
    reportNumber: 1278197,
    reportType: "Governor's Report",
    reporterFirstName: 'DILBNELIWA',
    reporterLastName: 'LINDAYLA',
    reportTime: '2016-04-16T12:50:00',
    hearings: [
      {
        oicHearingId: 1697172,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-04-22T14:54:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'gwdugwd',
        comment: 'KK',
        results: [],
      },
      {
        oicHearingId: 1685061,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-18T09:00:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'BESSEYNU',
        heardByLastName: 'YASMEXIA',
        comment: 'ffbffb',
        results: [],
      },
      {
        oicHearingId: 1703906,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2016-05-12T09:30:00',
        establishment: 'Haverigg (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'UZCCUZC',
        results: [
          {
            oicOffenceCode: '51:1',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Commits any assault',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 26,
                effectiveDate: '2016-05-12T00:00:00',
                status: 'Immediate',
                statusDate: '2016-05-12T00:00:00',
                comment: 'xREMNsMOQvgrZbsnGtEZoxREMNsMOQvgrZbsnGtEZo',
                sanctionSeq: 5,
              },
            ],
          },
        ],
      },
    ],
  },
]

const adjudicationsSearch = {
  results: {
    content: [
      {
        adjudicationNumber: 1468919,
        reportTime: '2017-01-18T11:02:00',
        agencyIncidentId: 1447062,
        agencyId: 'KMI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '1468919/1',
            offenceCode: '51:21',
            offenceDescription: 'Intentionally fails to work properly or, being required to work, refuses to do so',
            findingCode: 'PROVED',
          },
        ],
      },
      {
        adjudicationNumber: 1270334,
        reportTime: '2016-03-03T15:59:00',
        agencyIncidentId: 1252122,
        agencyId: 'BCI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '1270334/1',
            offenceCode: '51:20',
            offenceDescription: 'Uses threatening, abusive or insulting words or behaviour',
            findingCode: 'APPEAL',
          },
        ],
      },
      {
        adjudicationNumber: 998947,
        reportTime: '2014-10-16T06:47:00',
        agencyIncidentId: 984422,
        agencyId: 'DNI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '998947/1',
            offenceCode: '51:12A',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            findingCode: 'PROVED',
          },
          {
            oicChargeId: '998947/1',
            offenceCode: '51:12A',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            findingCode: 'REF_POLICE',
          },
        ],
      },
      {
        adjudicationNumber: 998946,
        reportTime: '2014-10-16T06:44:00',
        agencyIncidentId: 984421,
        agencyId: 'DNI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '998946/1',
            offenceCode: '51:12A',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            findingCode: 'PROVED',
          },
          {
            oicChargeId: '998946/1',
            offenceCode: '51:12A',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            findingCode: 'REF_POLICE',
          },
        ],
      },
      {
        adjudicationNumber: 998945,
        reportTime: '2014-10-16T06:41:00',
        agencyIncidentId: 984420,
        agencyId: 'DNI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '998945/1',
            offenceCode: '51:12A',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            findingCode: 'PROVED',
          },
          {
            oicChargeId: '998945/1',
            offenceCode: '51:12A',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            findingCode: 'REF_POLICE',
          },
        ],
      },
      {
        adjudicationNumber: 104837,
        reportTime: '2007-12-09T00:00:00',
        agencyIncidentId: 103790,
        agencyId: 'WOI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '104837/1',
            offenceCode: '51:20',
            offenceDescription: 'Uses threatening, abusive or insulting words or behaviour',
            findingCode: 'DISMISSED',
          },
        ],
      },
      {
        adjudicationNumber: 104838,
        reportTime: '2003-04-01T00:00:00',
        agencyIncidentId: 103791,
        agencyId: 'WRI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '104838/1',
            offenceCode: '51:12A',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            findingCode: 'PROVED',
          },
        ],
      },
      {
        adjudicationNumber: 104840,
        reportTime: '2001-09-03T00:00:00',
        agencyIncidentId: 103793,
        agencyId: 'MRI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '104840/1',
            offenceCode: '51:4',
            offenceDescription: 'Fights with any person;',
            findingCode: 'QUASHED',
          },
        ],
      },
      {
        adjudicationNumber: 104839,
        reportTime: '2001-01-09T00:00:00',
        agencyIncidentId: 103792,
        agencyId: 'FBI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '104839/1',
            offenceCode: '51:1N',
            offenceDescription: 'Commits any assault - assault on non prison officer member of staff',
            findingCode: 'DISMISSED',
          },
        ],
      },
      {
        adjudicationNumber: 104841,
        reportTime: '2000-06-19T00:00:00',
        agencyIncidentId: 103794,
        agencyId: 'PNI',
        partySeq: 1,
        adjudicationCharges: [
          {
            oicChargeId: '104841/1',
            offenceCode: '51:9',
            offenceDescription:
              'Administers a controlled drug to himself or fails to prevent the administration of a controlled drug to him by another person (but subject to rule 52)',
            findingCode: 'PROVED',
          },
        ],
      },
    ],
    pageable: {
      pageNumber: 0,
      pageSize: 1000,
      sort: { empty: true, unsorted: true, sorted: false },
      offset: 0,
      paged: true,
      unpaged: false,
    },
    totalPages: 1,
    totalElements: 10,
    last: true,
    size: 1000,
    number: 0,
    sort: { empty: true, unsorted: true, sorted: false },
    first: true,
    numberOfElements: 10,
    empty: false,
  },
  offences: [
    {
      id: '9',
      code: '51:9',
      description:
        'Administers a controlled drug to himself or fails to prevent the administration of a controlled drug to him by another person (but subject to rule 52)',
    },
    { id: '81', code: '51:1N', description: 'Commits any assault - assault on non prison officer member of staff' },
    { id: '5', code: '51:4', description: 'Fights with any person;' },
    {
      id: '88',
      code: '51:12A',
      description:
        'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
    },
    {
      id: '17',
      code: '51:21',
      description: 'Intentionally fails to work properly or, being required to work, refuses to do so',
    },
    { id: '16', code: '51:20', description: 'Uses threatening, abusive or insulting words or behaviour' },
  ],
  agencies: [
    { agencyId: 'FBI', description: 'Forest Bank (HMP & YOI)', active: true },
    { agencyId: 'BCI', description: 'Buckley Hall (HMP)', active: true },
    { agencyId: 'DNI', description: 'Doncaster (HMP)', active: true },
    { agencyId: 'KMI', description: 'Kirkham (HMP)', active: true },
    { agencyId: 'MRI', description: 'Manchester (HMP)', active: true },
    { agencyId: 'PNI', description: 'Preston (HMP)', active: true },
    { agencyId: 'WOI', description: 'Wolds (HMP)', active: false },
    { agencyId: 'WRI', description: 'Whitemoor (HMP)', active: true },
  ],
}

const adjudications = [
  {
    adjudicationNumber: 1468919,
    incidentTime: '2017-01-18T11:02:00',
    establishment: 'Kirkham (HMP)',
    interiorLocation: 'Induction',
    incidentDetails:
      'llxtkKcUnoOLEMQKngDzNNPHPqTMqdNZsZfKjtaXZTFalqiweDsKjAZAbQFbopufNuWoFriMAIazDyEttLWaemaUplmYjUCmObPrhRIeMSJnzdtVbcCScVzllxtkKcUnoOLEMQKngDzNNPHPqTMqdNZsZfKjtaXZTFalqiweDsKjAZAbQFbopufNuWoFriMAIazDyEttLWaemaUplmYjUCmObPrhRIeMSJnzdtVbcCScVz',
    reportNumber: 1447062,
    reportType: "Governor's Report",
    reporterFirstName: 'ULVNECHE',
    reporterLastName: 'MELVAN',
    reportTime: '2017-01-18T11:02:00',
    hearings: [
      {
        oicHearingId: 1931177,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2017-01-19T09:43:00',
        establishment: 'Kirkham (HMP)',
        location: 'Seg Adjudication Room',
        otherRepresentatives: 'WntdxWntdx',
        results: [
          {
            oicOffenceCode: '51:21',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Intentionally fails to work properly or, being required to work, refuses to do so',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 10,
                effectiveDate: '2023-10-03T00:00:00',
                status: 'Prospective',
                statusDate: '2023-10-03T00:00:00',
                sanctionSeq: 13,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 1270334,
    incidentTime: '2016-03-03T15:59:00',
    establishment: 'Buckley Hall (HMP)',
    interiorLocation: 'Staff Mess',
    incidentDetails:
      'VjswhIBPgsNTXqKJsilwXwwaJzRBrQFQGNHhNgBWqnPboomXlVUoBDcfjKyZZGfnGUAlWMfiVBVjswhIBPgsNTXqKJsilwXwwaJzRBrQFQGNHhNgBWqnPboomXlVUoBDcfjKyZZGfnGUAlWMfiVB',
    reportNumber: 1252122,
    reportType: "Governor's Report",
    reporterFirstName: 'OLBDALIAN',
    reporterLastName: 'JOYCESA',
    reportTime: '2016-03-03T15:59:00',
    hearings: [
      {
        oicHearingId: 1647990,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-03-04T09:00:00',
        establishment: 'Buckley Hall (HMP)',
        location: 'Adjudication Room',
        results: [],
      },
      {
        oicHearingId: 1681878,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2016-04-14T09:00:00',
        establishment: 'Buckley Hall (HMP)',
        location: 'Adjudication Room',
        heardByFirstName: 'ANMUALRICHARD',
        heardByLastName: 'DONOPHER',
        comment: 'ltzltz',
        results: [
          {
            oicOffenceCode: '51:20',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Uses threatening, abusive or insulting words or behaviour',
            plea: 'Not guilty',
            finding: 'Quashed on Appeal',
            sanctions: [
              {
                sanctionType: 'Forfeiture of Privileges',
                sanctionDays: 7,
                effectiveDate: '2016-04-15T00:00:00',
                status: 'Quashed',
                statusDate: '2016-04-15T00:00:00',
                comment: 'pvNuAMpvNuA',
                sanctionSeq: 10,
              },
              {
                sanctionType: 'Forfeiture of Privileges',
                sanctionDays: 7,
                effectiveDate: '2016-04-15T00:00:00',
                status: 'Quashed',
                statusDate: '2016-04-15T00:00:00',
                comment: 'MKFGiHMKFGi',
                sanctionSeq: 11,
              },
              {
                sanctionType: 'Forfeiture of Privileges',
                sanctionDays: 7,
                effectiveDate: '2016-04-15T00:00:00',
                status: 'Quashed',
                statusDate: '2016-04-15T00:00:00',
                comment: 'ouo',
                sanctionSeq: 12,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 998947,
    incidentTime: '2014-10-16T06:47:00',
    establishment: 'Doncaster (HMP)',
    interiorLocation: 'Servery',
    incidentDetails: 'WnZJMuhdyCObwatxTdxAIVJIwDIyWnZJMuhdyCObwatxTdxAIVJIwDIy',
    reportNumber: 984422,
    reportType: "Governor's Report",
    reporterFirstName: 'UHOYNEKE',
    reporterLastName: 'AMBENTINO',
    reportTime: '2014-10-16T06:47:00',
    hearings: [
      {
        oicHearingId: 1289218,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2014-11-24T13:31:00',
        establishment: 'Doncaster (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'KEKKEK',
        results: [
          {
            oicOffenceCode: '51:12A',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 21,
                effectiveDate: '2014-11-24T00:00:00',
                status: 'Immediate',
                statusDate: '2014-11-24T00:00:00',
                sanctionSeq: 9,
              },
            ],
          },
        ],
      },
      {
        oicHearingId: 1262643,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2014-10-16T09:58:00',
        establishment: 'Doncaster (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'WcGWcG',
        results: [
          {
            oicOffenceCode: '51:12A',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            plea: 'Not guilty',
            finding: 'Referred to Police',
            sanctions: [],
          },
        ],
      },
      {
        oicHearingId: 1267078,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2014-10-23T14:18:00',
        establishment: 'Doncaster (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'yYFPyYF',
        comment: 'cKscKs',
        results: [],
      },
    ],
  },
  {
    adjudicationNumber: 998946,
    incidentTime: '2014-10-16T06:44:00',
    establishment: 'Doncaster (HMP)',
    interiorLocation: 'Recreation  Rm',
    incidentDetails: 'QXFKDFgKgsbCMgUHjyGBGxtcCocQXFKDFgKgsbCMgUHjyGBGxtcCoc',
    reportNumber: 984421,
    reportType: "Governor's Report",
    reporterFirstName: 'UHOYNEKE',
    reporterLastName: 'AMBENTINO',
    reportTime: '2014-10-16T06:44:00',
    hearings: [
      {
        oicHearingId: 1289217,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2014-11-24T13:30:00',
        establishment: 'Doncaster (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'HPqHPq',
        results: [
          {
            oicOffenceCode: '51:12A',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 21,
                effectiveDate: '2014-11-24T00:00:00',
                status: 'Immediate',
                statusDate: '2014-11-24T00:00:00',
                sanctionSeq: 8,
              },
            ],
          },
        ],
      },
      {
        oicHearingId: 1262642,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2014-10-16T09:57:00',
        establishment: 'Doncaster (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'LhYLhY',
        results: [
          {
            oicOffenceCode: '51:12A',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            plea: 'Not guilty',
            finding: 'Referred to Police',
            sanctions: [],
          },
        ],
      },
      {
        oicHearingId: 1267077,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2014-10-23T14:17:00',
        establishment: 'Doncaster (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'TjysTjy',
        comment: 'SKFSKF',
        results: [],
      },
    ],
  },
  {
    adjudicationNumber: 998945,
    incidentTime: '2014-10-16T06:41:00',
    establishment: 'Doncaster (HMP)',
    interiorLocation: 'Recreation  Rm',
    incidentDetails: 'flVghKnvWbTuwhQQhRuHxctYWCGpFOVflVghKnvWbTuwhQQhRuHxctYWCGpFOV',
    reportNumber: 984420,
    reportType: "Governor's Report",
    reporterFirstName: 'UHOYNEKE',
    reporterLastName: 'AMBENTINO',
    reportTime: '2014-10-16T06:41:00',
    hearings: [
      {
        oicHearingId: 1289216,
        hearingType: 'Independent Adjudicator Hearing Adult',
        hearingTime: '2014-11-24T13:30:00',
        establishment: 'Doncaster (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'nMKnMK',
        results: [
          {
            oicOffenceCode: '51:12A',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Forfeiture of Privileges',
                sanctionDays: 21,
                effectiveDate: '2014-11-24T00:00:00',
                status: 'Immediate',
                statusDate: '2014-11-24T00:00:00',
                sanctionSeq: 7,
              },
            ],
          },
        ],
      },
      {
        oicHearingId: 1262641,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2014-10-16T09:57:00',
        establishment: 'Doncaster (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'cfvcfv',
        results: [
          {
            oicOffenceCode: '51:12A',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            plea: 'Not guilty',
            finding: 'Referred to Police',
            sanctions: [],
          },
        ],
      },
      {
        oicHearingId: 1267076,
        hearingType: "Governor's Hearing Adult",
        hearingTime: '2014-10-23T14:17:00',
        establishment: 'Doncaster (HMP)',
        location: 'Adjudication Room',
        otherRepresentatives: 'XAEeXAE',
        comment: 'oeyoey',
        results: [],
      },
    ],
  },
  {
    adjudicationNumber: 104837,
    incidentTime: '2007-12-09T00:00:00',
    establishment: 'Wolds (HMP)',
    interiorLocation: 'Wolds (HMP)',
    incidentDetails: 'ZDFTPdPYZDFTPdP',
    reportNumber: 103790,
    reportType: 'Miscellaneous',
    reporterFirstName: 'XTAG',
    reporterLastName: 'XTAG',
    reportTime: '2007-12-09T00:00:00',
    hearings: [
      {
        oicHearingId: 105775,
        hearingType: "Governor's Hearing",
        hearingTime: '2007-12-13T00:00:00',
        establishment: 'Wolds (HMP)',
        location: 'Wolds (HMP)',
        otherRepresentatives: 'jXLkjvKLTMgezdjXLkjvKLTMgez',
        comment: 'uYYMvlLZuYYMvlL',
        results: [
          {
            oicOffenceCode: '51:20',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Uses threatening, abusive or insulting words or behaviour',
            plea: 'Not guilty',
            finding: 'Discharged',
            sanctions: [],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 104838,
    incidentTime: '2003-04-01T00:00:00',
    establishment: 'Whitemoor (HMP)',
    interiorLocation: 'Whitemoor (HMP)',
    incidentDetails: 'ATFStWzSATFStWz',
    reportNumber: 103791,
    reportType: 'Miscellaneous',
    reporterFirstName: 'XTAG',
    reporterLastName: 'XTAG',
    reportTime: '2003-04-01T00:00:00',
    hearings: [
      {
        oicHearingId: 105776,
        hearingType: "Governor's Hearing",
        hearingTime: '2003-04-03T00:00:00',
        establishment: 'Whitemoor (HMP)',
        location: 'Whitemoor (HMP)',
        otherRepresentatives: 'YwLiCLyKidFsKRYwLiCLyKidFsK',
        comment: 'XKTlCeTaXKTlCeT',
        results: [
          {
            oicOffenceCode: '51:12A',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Has in his possession - (a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have - possession of unauthorised items',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Stoppage of Earnings (%)',
                sanctionDays: 7,
                compensationAmount: 100,
                effectiveDate: '2003-04-03T00:00:00',
                status: 'Immediate',
                comment: 'dlxpnnnEdlxpnnn',
                sanctionSeq: 1,
              },
              {
                sanctionType: 'Forfeiture of Privileges',
                sanctionDays: 7,
                compensationAmount: 0,
                effectiveDate: '2003-04-03T00:00:00',
                status: 'Immediate',
                comment: 'MfaqZvuWMfaqZvu',
                sanctionSeq: 2,
              },
              {
                sanctionType: 'Canteen Facilities',
                effectiveDate: '2003-04-03T00:00:00',
                status: 'Immediate',
                comment: 'OeHpoHHbqImLluhUOeHpoHHbqImLluh',
                sanctionSeq: 3,
              },
              {
                sanctionType: 'Cellular Confinement',
                sanctionDays: 7,
                compensationAmount: 0,
                effectiveDate: '2003-04-03T00:00:00',
                status: 'Suspended',
                comment: 'OrZpTGuZOrZpTGu',
                sanctionSeq: 4,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 104840,
    incidentTime: '2001-09-03T00:00:00',
    establishment: 'Manchester (HMP)',
    interiorLocation: 'Manchester (HMP)',
    incidentDetails: 'eBKnWIlgeBKnWIl',
    reportNumber: 103793,
    reportType: 'Miscellaneous',
    reporterFirstName: 'XTAG',
    reporterLastName: 'XTAG',
    reportTime: '2001-09-03T00:00:00',
    hearings: [
      {
        oicHearingId: 105778,
        hearingType: "Governor's Hearing",
        hearingTime: '2001-09-08T00:00:00',
        establishment: 'Manchester (HMP)',
        location: 'Manchester (HMP)',
        otherRepresentatives: 'EqveqgjiRfYfwPEqveqgjiRfYfw',
        comment: 'FOwiFsoYFOwiFso',
        results: [
          {
            oicOffenceCode: '51:4',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Fights with any person;',
            plea: 'Not guilty',
            finding: 'Quashed',
            sanctions: [],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 104839,
    incidentTime: '2001-01-09T00:00:00',
    establishment: 'Forest Bank (HMP & YOI)',
    interiorLocation: 'Forest Bank (HMP & YOI)',
    incidentDetails: 'fQkiVFjzfQkiVFj',
    reportNumber: 103792,
    reportType: 'Miscellaneous',
    reporterFirstName: 'XTAG',
    reporterLastName: 'XTAG',
    reportTime: '2001-01-09T00:00:00',
    hearings: [
      {
        oicHearingId: 105777,
        hearingType: "Governor's Hearing",
        hearingTime: '2001-01-10T00:00:00',
        establishment: 'Forest Bank (HMP & YOI)',
        location: 'Forest Bank (HMP & YOI)',
        otherRepresentatives: 'MVqNJbrPLkVvMVqNJbrPLkV',
        comment: 'eNJZPfcteNJZPfc',
        results: [
          {
            oicOffenceCode: '51:1N',
            offenceType: 'Prison Rule 51',
            offenceDescription: 'Commits any assault - assault on non prison officer member of staff',
            plea: 'Not guilty',
            finding: 'Discharged',
            sanctions: [],
          },
        ],
      },
    ],
  },
  {
    adjudicationNumber: 104841,
    incidentTime: '2000-06-19T00:00:00',
    establishment: 'Preston (HMP)',
    interiorLocation: 'Preston (HMP)',
    incidentDetails: 'ELRFxDTkELRFxDT',
    reportNumber: 103794,
    reportType: 'Miscellaneous',
    reporterFirstName: 'XTAG',
    reporterLastName: 'XTAG',
    reportTime: '2000-06-19T00:00:00',
    hearings: [
      {
        oicHearingId: 105779,
        hearingType: "Governor's Hearing",
        hearingTime: '2000-07-25T00:00:00',
        establishment: 'Preston (HMP)',
        location: 'Preston (HMP)',
        otherRepresentatives: 'YKGHzkGyxUWYYCYKGHzkGyxUWYY',
        comment: 'KVJtbKuDKVJtbKu',
        results: [
          {
            oicOffenceCode: '51:9',
            offenceType: 'Prison Rule 51',
            offenceDescription:
              'Administers a controlled drug to himself or fails to prevent the administration of a controlled drug to him by another person (but subject to rule 52)',
            plea: 'Guilty',
            finding: 'Charge Proved',
            sanctions: [
              {
                sanctionType: 'Stoppage of Earnings (amount)',
                sanctionDays: 7,
                compensationAmount: 3,
                effectiveDate: '2000-07-25T00:00:00',
                status: 'Immediate',
                comment: 'oheiHhcAoheiHhc',
                sanctionSeq: 5,
              },
              {
                sanctionType: 'Additional Days Added',
                sanctionDays: 7,
                compensationAmount: 0,
                effectiveDate: '2009-10-18T00:00:00',
                status: 'Prospective',
                comment: 'XrxQVLIUXrxQVLI',
                sanctionSeq: 6,
              },
            ],
          },
        ],
      },
    ],
  },
]
export { adjudicationsNoReview, adjudicationsSearchNoReview, adjudicationsSearch, adjudications }
