---
# Per environment values which override defaults in hmpps-adjustments/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: adjust-release-dates-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://adjust-release-dates-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    ADJUSTMENTS_API_URL: "https://adjustments-api-dev.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_URL: "https://calculate-release-dates-dev.hmpps.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICES_URL: "https://digital-dev.prison.service.justice.gov.uk"
    IDENTIFY_REMAND_PERIODS_URL: "https://identify-remand-periods-dev.hmpps.service.justice.gov.uk"
    IDENTIFY_REMAND_PERIODS_API_URL: "https://identify-remand-periods-api-dev.hmpps.service.justice.gov.uk"
    ADJUDICATIONS_API_URL: "https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    PRISONER_SEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    COMMON_COMPONENTS_ENABLED: 'true'
<<<<<<< HEAD
    COURT_CASES_RELEASE_DATES_API_URL: "https://court-cases-release-dates-api-dev.hmpps.service.justice.gov.uk"
    DISPLAY_ADA_INTERCEPT: 'false'
=======
    TIME_SPENT_IN_CUSTODY_ABROAD_ENABLED: 'true'
>>>>>>> 79aadf8 (ADJST-921 Add time spent in custody abroad adjustment type)

  # Switches off the allow list in the DEV env only.
  allowlist: null
  
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: legacy-replacement-alerts-non-prod
