---
# Per environment values which override defaults in hmpps-adjustments/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: adjust-release-dates-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://adjust-release-dates-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    ADJUSTMENTS_API_URL: "https://adjustments-api-preprod.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_URL: "https://calculate-release-dates-preprod.hmpps.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICES_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    IDENTIFY_REMAND_PERIODS_URL: "https://identify-remand-periods-preprod.hmpps.service.justice.gov.uk"
    IDENTIFY_REMAND_PERIODS_API_URL: "https://identify-remand-periods-api-preprod.hmpps.service.justice.gov.uk"
    ADJUDICATIONS_API_URL: "https://manage-adjudications-api-preprod.hmpps.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"

  allowlist:
    cymulate-1: 54.217.50.18/32
    cymulate-2: 52.208.202.111/32
    cymulate-3: 52.49.144.209/32
    security-testing-1: 217.46.35.148/32 # Remove on 26-03-2024
    security-testing-2: 100.64.14.172/32 # Remove on 26-03-2024
    groups:
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  alertSeverity: legacy-replacements-alerts-non-prod
